backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/upload" # Where media files will be stored
public_folder: "/upload" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Instagram"
            name: "instagram"
            widget: "string"
          - label: "LinkedIn"
            name: "linkedin"
            widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/home.mdx"
        fields:
          - label: "Desktop images"
            name: "desktopImages"
            widget: "list"
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image, required: true}
          - label: "About"
            name: "about"
            widget: "markdown"
          - label: "Address"
            name: "address"
            widget: "markdown"
          - label: "Hours"
            name: "hours"
            widget: "markdown"
          - label: "Contact"
            name: "contact"
            widget: "markdown"
          - label: "Menu Philosophy"
            name: "menu_philosophy"
            widget: "markdown"
          - label: "Menu"
            name: "menu"
            widget: "file"
            media_library:
              config:
                multiple: false
          - lable: "Order online link"
            name: "order_online_link"
            widget: "string"
          - lable: "Book online link"
            name: "book_online_link"
            widget: "string"